### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by radu-matei** [Azure/brigade#747]
This issue tracks the re-vamping of the documentation for Brigade - specifically, clean sections for user guide, coding reference, admin guide.

related: #748, #79, #314, #450, #451. #506, #595

**TODO**
 - [x] topics navigation - https://github.com/Azure/brigade/pull/782
 - [x] update (or ensure content covered and remove) `docs/topics/install.md` - https://github.com/Azure/brigade/pull/783
 - [x] remove "experimental" mentions -> https://github.com/Azure/brigade/pull/791
 - [x] #79 -> https://github.com/Azure/brigade/pull/784
 - [x] #314 -> https://github.com/Azure/brigade/pull/785
 - [x] #450 
 - [x] #451 -> https://github.com/Azure/brigade/pull/791
 - [x] Update references around Brigade project install/upgrade to use `brig` cli as opposed to (deprecated) Helm chart approach -> https://github.com/Azure/brigade/pull/794
 
(TODO list added by vdice 1/23/19; last edited 1/31/19)

**Comment by dgkanatsios** [comment]
One thing that I think should be fixed is the navigation in [topics](https://azure.github.io/brigade/topics/). As soon as I visit any page, e.g. [this](https://azure.github.io/brigade/topics/projects.html), there is no easy way to return to the table of contents unless I use browser's back button.

**Comment by vdice** [comment]
I'll take this one on.   As the description is a fairly far-reaching, I'll start to ensure all of the referenced tickets are covered, as well as the note from @dgkanatsios and then put up a PR...

**Comment by radu-matei** [comment]
Question: currently, the landing page is on one domain (`brigade.sh`), while the documentation is directly on GitHub Pages - would it make sense to move the docs under `docs.brigade.sh`?

If so, I'll add an item on the list.
Thanks!

**Comment by vdice** [comment]
We're getting close!!  Added @radu-matei as an asignee as I believe he's cooking up docs around remote/local js module use.

**Comment by radu-matei** [comment]
Yes!!
Thanks a lot, everyone!

And particularly, thanks to @vdice, who has been absolutely fantastic working on docs last few weeks.
